version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      # Build the Docker images
      - echo Building the production Docker image...
      - docker build -t paullamxd/react-frontend ./client
      - docker build -t paullamxd/node-backend ./server
      # Log in to the Docker CLI
      # - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push paullamxd/react-frontend
      - docker push paullamxd/node-backend