version: '3'

services:
  backend:
    env_file:
        "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "paullamxd/node-backend"
    ports:
      - "8081:8080"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "paullamxd/react-frontend"
    ports:
      - "3001:3000"
    links:
      - "backend:be"